/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package owlneo;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lara
 */
public class Main extends javax.swing.JFrame {

    MainSup support;
    /*final Vector delimiters;
    final Vector literals;*/
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        /*delimiters = new Vector();
        delimiters.add(";");
        delimiters.add(",");
        delimiters.add("tab");
        delimiters.add("space");
        literals = new Vector();
        literals.add("\"");
        literals.add("\'");*/
        support = new MainSup();
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        individualDialog = new javax.swing.JDialog();
        OWLFileDialog = new javax.swing.JDialog();
        OWLFileChooser = new javax.swing.JFileChooser();
        AboutDialog = new javax.swing.JDialog();
        emailAbout = new java.awt.Label();
        aboutClose = new java.awt.Button();
        CSVFileChooserDialog = new javax.swing.JDialog();
        DelimLabel = new javax.swing.JLabel();
        Litlabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        CSVSemicolonOption = new javax.swing.JRadioButton();
        CSVCommaOption = new javax.swing.JRadioButton();
        CSVTabOption = new javax.swing.JRadioButton();
        CSVSpaceOption = new javax.swing.JRadioButton();
        CSVLitDoubleQuoteOption = new javax.swing.JRadioButton();
        CSVLitSingleQuoteOption = new javax.swing.JRadioButton();
        CSVLitNoQuoteOption = new javax.swing.JRadioButton();
        CSVFileChooser = new javax.swing.JFileChooser();
        OWLError = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DelimGrp = new javax.swing.ButtonGroup();
        LitGrp = new javax.swing.ButtonGroup();
        CSVErrorDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        mainBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenOWLMenu = new javax.swing.JMenuItem();
        ReadCSVMenu = new javax.swing.JMenuItem();
        ExitMenu = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        CypherMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        individualDialog.setTitle("Add Individual");
        individualDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        individualDialog.setModal(true);
        individualDialog.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout individualDialogLayout = new javax.swing.GroupLayout(individualDialog.getContentPane());
        individualDialog.getContentPane().setLayout(individualDialogLayout);
        individualDialogLayout.setHorizontalGroup(
            individualDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        individualDialogLayout.setVerticalGroup(
            individualDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        individualDialog.getAccessibleContext().setAccessibleName("");

        OWLFileDialog.setTitle("Select OWL File");
        OWLFileDialog.setLocationByPlatform(true);
        OWLFileDialog.setMinimumSize(new java.awt.Dimension(700, 480));
        OWLFileDialog.setModal(true);
        OWLFileDialog.setName("filedialog"); // NOI18N
        OWLFileDialog.setResizable(false);

        OWLFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OWLFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OWLFileDialogLayout = new javax.swing.GroupLayout(OWLFileDialog.getContentPane());
        OWLFileDialog.getContentPane().setLayout(OWLFileDialogLayout);
        OWLFileDialogLayout.setHorizontalGroup(
            OWLFileDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OWLFileDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OWLFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        OWLFileDialogLayout.setVerticalGroup(
            OWLFileDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OWLFileDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OWLFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        AboutDialog.setMinimumSize(new java.awt.Dimension(400, 300));
        AboutDialog.setName("aboutdialog"); // NOI18N
        AboutDialog.setResizable(false);

        emailAbout.setText("Contact: lara.ps.silva@gmail.com");

        aboutClose.setLabel("Close");
        aboutClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AboutDialogLayout = new javax.swing.GroupLayout(AboutDialog.getContentPane());
        AboutDialog.getContentPane().setLayout(AboutDialogLayout);
        AboutDialogLayout.setHorizontalGroup(
            AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutDialogLayout.createSequentialGroup()
                .addGroup(AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AboutDialogLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(emailAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AboutDialogLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(aboutClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        AboutDialogLayout.setVerticalGroup(
            AboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AboutDialogLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(emailAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(aboutClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        CSVFileChooserDialog.setTitle("Select CSV File");
        CSVFileChooserDialog.setAlwaysOnTop(true);
        CSVFileChooserDialog.setMinimumSize(new java.awt.Dimension(700, 480));
        CSVFileChooserDialog.setModal(true);
        CSVFileChooserDialog.setResizable(false);

        DelimLabel.setText("Delimiter:");

        Litlabel.setText("Literal value marker:");

        DelimGrp.add(CSVSemicolonOption);
        CSVSemicolonOption.setText(";");
        CSVSemicolonOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVSemicolonOptionActionPerformed(evt);
            }
        });

        DelimGrp.add(CSVCommaOption);
        CSVCommaOption.setText(",");
        CSVCommaOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVCommaOptionActionPerformed(evt);
            }
        });

        DelimGrp.add(CSVTabOption);
        CSVTabOption.setText("Tab");
        CSVTabOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVTabOptionActionPerformed(evt);
            }
        });

        DelimGrp.add(CSVSpaceOption);
        CSVSpaceOption.setText("Space");
        CSVSpaceOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVSpaceOptionActionPerformed(evt);
            }
        });

        LitGrp.add(CSVLitDoubleQuoteOption);
        CSVLitDoubleQuoteOption.setText("\"");
        CSVLitDoubleQuoteOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVLitDoubleQuoteOptionActionPerformed(evt);
            }
        });

        LitGrp.add(CSVLitSingleQuoteOption);
        CSVLitSingleQuoteOption.setText("'");

        LitGrp.add(CSVLitNoQuoteOption);
        CSVLitNoQuoteOption.setText("<nothing>");
        CSVLitNoQuoteOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CSVLitNoQuoteOptionMouseEntered(evt);
            }
        });

        CSVFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSVFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CSVFileChooserDialogLayout = new javax.swing.GroupLayout(CSVFileChooserDialog.getContentPane());
        CSVFileChooserDialog.getContentPane().setLayout(CSVFileChooserDialogLayout);
        CSVFileChooserDialogLayout.setHorizontalGroup(
            CSVFileChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CSVFileChooserDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CSVFileChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(CSVFileChooserDialogLayout.createSequentialGroup()
                        .addGroup(CSVFileChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DelimLabel)
                            .addComponent(Litlabel)
                            .addComponent(CSVSemicolonOption)
                            .addComponent(CSVCommaOption)
                            .addComponent(CSVTabOption)
                            .addComponent(CSVSpaceOption)
                            .addComponent(CSVLitDoubleQuoteOption)
                            .addComponent(CSVLitSingleQuoteOption)
                            .addComponent(CSVLitNoQuoteOption))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(CSVFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CSVFileChooserDialogLayout.setVerticalGroup(
            CSVFileChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CSVFileChooserDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CSVFileChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CSVFileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .addGroup(CSVFileChooserDialogLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(DelimLabel)
                        .addGap(18, 18, 18)
                        .addComponent(CSVSemicolonOption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CSVCommaOption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CSVTabOption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CSVSpaceOption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Litlabel)
                        .addGap(18, 18, 18)
                        .addComponent(CSVLitDoubleQuoteOption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CSVLitSingleQuoteOption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CSVLitNoQuoteOption)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        OWLError.setMinimumSize(new java.awt.Dimension(440, 200));
        OWLError.setModal(true);
        OWLError.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        OWLError.setResizable(false);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Error reading the provided OWL file.");

        jLabel2.setText("Please verify if the file is in the OWL/RDF format and try again.");

        javax.swing.GroupLayout OWLErrorLayout = new javax.swing.GroupLayout(OWLError.getContentPane());
        OWLError.getContentPane().setLayout(OWLErrorLayout);
        OWLErrorLayout.setHorizontalGroup(
            OWLErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OWLErrorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OWLErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OWLErrorLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OWLErrorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(181, 181, 181))))
            .addGroup(OWLErrorLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        OWLErrorLayout.setVerticalGroup(
            OWLErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OWLErrorLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(28, 28, 28))
        );

        CSVErrorDialog.setTitle("CSV Error");
        CSVErrorDialog.setMinimumSize(new java.awt.Dimension(200, 100));
        CSVErrorDialog.setModal(true);
        CSVErrorDialog.setName("csvErrorDialog"); // NOI18N
        CSVErrorDialog.setResizable(false);

        jLabel3.setText("Error loading CSV File");

        jButton2.setText(" Close ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CSVErrorDialogLayout = new javax.swing.GroupLayout(CSVErrorDialog.getContentPane());
        CSVErrorDialog.getContentPane().setLayout(CSVErrorDialogLayout);
        CSVErrorDialogLayout.setHorizontalGroup(
            CSVErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CSVErrorDialogLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(25, 25, 25))
            .addGroup(CSVErrorDialogLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CSVErrorDialogLayout.setVerticalGroup(
            CSVErrorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CSVErrorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OWL2Neo");

        FileMenu.setText("File");

        OpenOWLMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        OpenOWLMenu.setText("Open OWL");
        OpenOWLMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenOWLMenuActionPerformed(evt);
            }
        });
        FileMenu.add(OpenOWLMenu);

        ReadCSVMenu.setText("Read CSV");
        ReadCSVMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadCSVMenuActionPerformed(evt);
            }
        });
        FileMenu.add(ReadCSVMenu);

        ExitMenu.setText("Exit");
        ExitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuActionPerformed(evt);
            }
        });
        FileMenu.add(ExitMenu);

        mainBar.add(FileMenu);

        EditMenu.setText("Edit");

        jMenuItem6.setText("Add Individual");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        EditMenu.add(jMenuItem6);

        jMenuItem7.setText("Add Class");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        EditMenu.add(jMenuItem7);

        jMenuItem8.setText("Add Information");
        EditMenu.add(jMenuItem8);

        mainBar.add(EditMenu);

        CypherMenu.setText("Cypher Queries");

        jMenuItem4.setText("Get ontology create script");
        CypherMenu.add(jMenuItem4);

        jMenuItem5.setText("Get populating queries");
        CypherMenu.add(jMenuItem5);

        mainBar.add(CypherMenu);

        HelpMenu.setText("Help");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem9.setText("About");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        HelpMenu.add(jMenuItem9);

        mainBar.add(HelpMenu);

        setJMenuBar(mainBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        AboutDialog.setVisible(true);
        AboutDialog.toFront();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void OpenOWLMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenOWLMenuActionPerformed
        // TODO add your handling code here:
        OWLFileDialog.setVisible(true);
        OWLFileDialog.toFront();
    }//GEN-LAST:event_OpenOWLMenuActionPerformed

    private void OWLFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OWLFileChooserActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals("CancelSelection")){
            OWLFileDialog.setVisible(false);
            
        }
        else{
            boolean success = support.setupOWL(OWLFileChooser.getSelectedFile());
            if (!success){
                OWLError.setVisible(true);
            }
            else{
                System.out.println(OWLFileChooser.getSelectedFile().getName());
                OWLFileDialog.setVisible(false);
            }
        }
    }//GEN-LAST:event_OWLFileChooserActionPerformed

    private void aboutCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutCloseActionPerformed
        // TODO add your handling code here:
        AboutDialog.setVisible(false);
    }//GEN-LAST:event_aboutCloseActionPerformed

    private void ExitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuActionPerformed
        // TODO add save and all that code
        System.exit(0);
    }//GEN-LAST:event_ExitMenuActionPerformed

    private void ReadCSVMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadCSVMenuActionPerformed
        // TODO add your handling code here:
        CSVFileChooserDialog.setVisible(true);
        CSVFileChooserDialog.toFront();
    }//GEN-LAST:event_ReadCSVMenuActionPerformed

    private void CSVFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVFileChooserActionPerformed
        // TODO add your handling code here:
        if (evt.getActionCommand().equals("CancelSelection")){
            CSVFileChooserDialog.setVisible(false);
        }
        if (evt.getActionCommand().equals("ApproveSelection")){
            File csvFile = CSVFileChooser.getSelectedFile();
            Path filepath = Paths.get(csvFile.getPath());
            boolean righttype = false;
            try {
                righttype = Files.probeContentType(filepath).matches("text/csv");
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                righttype = false;
            }
            
            boolean CSVsuccess = support.setupCSV(csvFile);
            //verifies if the class was created with success and closes the
            //filechooser dialog window
            
            if (CSVsuccess && righttype){
                CSVFileChooserDialog.setVisible(false);
            }
            else {
                CSVErrorDialog.setVisible(true);
            }
            
                
        }
    }//GEN-LAST:event_CSVFileChooserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        OWLError.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CSVSemicolonOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVSemicolonOptionActionPerformed
        // TODO add your handling code here:
        if (CSVSemicolonOption.isSelected()){
            support.setupCSVDelim(";");
        }
        System.out.println(support.getCSVDelim());
    }//GEN-LAST:event_CSVSemicolonOptionActionPerformed

    private void CSVCommaOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVCommaOptionActionPerformed
        // TODO add your handling code here:
        if (CSVCommaOption.isSelected()){
            support.setupCSVDelim(",");           
        }
        System.out.println(support.getCSVDelim());
    }//GEN-LAST:event_CSVCommaOptionActionPerformed

    private void CSVLitDoubleQuoteOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVLitDoubleQuoteOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CSVLitDoubleQuoteOptionActionPerformed

    private void CSVLitNoQuoteOptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CSVLitNoQuoteOptionMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CSVLitNoQuoteOptionMouseEntered

    private void CSVTabOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVTabOptionActionPerformed
        // TODO add your handling code here:
        if (CSVTabOption.isSelected()){
            support.setupCSVDelim("\t");
        }
        System.out.println(support.getCSVDelim());
    }//GEN-LAST:event_CSVTabOptionActionPerformed

    private void CSVSpaceOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CSVSpaceOptionActionPerformed
        // TODO add your handling code here:
        if (CSVSpaceOption.isSelected()){
            support.setupCSVDelim(" ");
        }
        System.out.println(support.getCSVDelim());
    }//GEN-LAST:event_CSVSpaceOptionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CSVErrorDialog.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog AboutDialog;
    private javax.swing.JRadioButton CSVCommaOption;
    private javax.swing.JDialog CSVErrorDialog;
    private javax.swing.JFileChooser CSVFileChooser;
    private javax.swing.JDialog CSVFileChooserDialog;
    private javax.swing.JRadioButton CSVLitDoubleQuoteOption;
    private javax.swing.JRadioButton CSVLitNoQuoteOption;
    private javax.swing.JRadioButton CSVLitSingleQuoteOption;
    private javax.swing.JRadioButton CSVSemicolonOption;
    private javax.swing.JRadioButton CSVSpaceOption;
    private javax.swing.JRadioButton CSVTabOption;
    private javax.swing.JMenu CypherMenu;
    private javax.swing.ButtonGroup DelimGrp;
    private javax.swing.JLabel DelimLabel;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenuItem ExitMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.ButtonGroup LitGrp;
    private javax.swing.JLabel Litlabel;
    private javax.swing.JDialog OWLError;
    private javax.swing.JFileChooser OWLFileChooser;
    private javax.swing.JDialog OWLFileDialog;
    private javax.swing.JMenuItem OpenOWLMenu;
    private javax.swing.JMenuItem ReadCSVMenu;
    private java.awt.Button aboutClose;
    private java.awt.Label emailAbout;
    private javax.swing.JDialog individualDialog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenuBar mainBar;
    // End of variables declaration//GEN-END:variables
}
